### ISSUE TITLE
Plugin download?

### ISSUE THREAD

**Issue by mixMugz** [bwRavencl/X-Gamepad#2]
Hi! How i can download your plugin? There is only source.

**Comment by bwRavencl** [comment]
Hi there!
I'm very sorry but unfortunately I do not provide compiled binaries of X-Gamepad at this point in time.  
A while ago I began revamping the whole build process to be able to provide automatic builds whenever I push a change. However I did not not complete these changes as of right now.  
At this point I also cannot tell you for sure if and if at all I will pick up development of X-Gamepad at all again in the future.  
If you have the necessary knowledge I would recommend that you try to compile X-Gamepad yourself for your respective platform. Please also note that macOS and Linux support is  in a bit of sorry and untested state as of right now.
